[package]
name = "practicas-basicas"
version = "0.1.0"
authors = ["VentGrey <omarpurataf@gmail.com>"]

[[bin]]
name = "1.0"
path = "src/1_0/*.rs"

[[bin]]
name = "2.0"
path ="src/2_0/*.rs"

[[bin]]
name = "3.0"
path = "src/3_0/*.rs"

[dependencies]
